<a href="https://colab.research.google.com/github/Sandwhaletree/Mai_Finlab/blob/main/%E8%82%A1%E7%A5%A8%E8%B2%A1%E5%8B%99%E5%88%86%E6%9E%90/B01_%E5%8F%B0%E8%82%A1%E9%99%A4%E6%AC%8A%E6%81%AF%E5%A0%B1%E8%A1%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* [FinMind Data-台股除權息報表](https://medium.com/finmind/finmind-data-%E5%8F%B0%E8%82%A1%E9%99%A4%E6%AC%8A%E6%81%AF%E5%A0%B1%E8%A1%A8-125c19616b41)
* [FinMind Web](https://finmind.github.io/api_usage_count/)

In [6]:
from urllib.request import urlretrieve #file.findminddata0725.txt
url='https://github.com/Sandwhaletree/Mai_Finlab/raw/main/%E8%82%A1%E7%A5%A8%E8%B2%A1%E5%8B%99%E5%88%86%E6%9E%90'
urlretrieve(url,"1.txt")

('1.txt', <http.client.HTTPMessage at 0x795b6c9feef0>)

In [10]:
import pandas as pd
name =pd.read_csv("1.txt")
TOKEN=name

In [11]:
import datetime
import requests
import pandas as pd

stock_ids = ['2884', '5880', '2891', '2330', '2881', '2892', '1101', '1102', '2454', '1216', '002608']

start_date = datetime.date(2023, 7, 25)
end_date = start_date + datetime.timedelta(days=30)

url = "https://api.finmindtrade.com/api/v4/data"
date_format = '%Y-%m-%d'
merge_data = []
for stock_id in stock_ids:
    print(f"Get stock_id:{stock_id}")
    parameter = {
        "dataset": "TaiwanStockDividend",
        "data_id":stock_id,
        "start_date": datetime.datetime.strftime(start_date, date_format),
        "end_date": datetime.datetime.strftime(end_date, date_format),
        "token": TOKEN, # 參考登入，獲取金鑰
    }
    data = requests.get(url, params=parameter)
    data = data.json()
    TaiwanStockDividend = pd.DataFrame(data['data'])
    if not TaiwanStockDividend.empty:
        TaiwanStockDividend = TaiwanStockDividend[
            [
                'date',
                'stock_id',
                'StockExDividendTradingDate',
                'CashExDividendTradingDate',
                'CashDividendPaymentDate',
                'StockEarningsDistribution',
                'StockStatutorySurplus',
                'CashEarningsDistribution',
                'CashStatutorySurplus'
            ]
        ]
        TaiwanStockDividend['TotalStock'] = TaiwanStockDividend['StockEarningsDistribution'] + TaiwanStockDividend['StockStatutorySurplus']
        TaiwanStockDividend['TotalCash'] = TaiwanStockDividend['CashEarningsDistribution'] + TaiwanStockDividend['CashStatutorySurplus']
        merge_data.append(TaiwanStockDividend)

merge_datas = pd.concat(merge_data, axis=0)
merge_datas = merge_datas.sort_values(by=["CashExDividendTradingDate"])
merge_datas = merge_datas[
    [
        'date',
        'stock_id',
        'StockExDividendTradingDate',
        'CashExDividendTradingDate',
        'CashDividendPaymentDate',
        'TotalStock','TotalCash'
    ]
]
merge_datas

Get stock_id:2884
Get stock_id:5880
Get stock_id:2891
Get stock_id:2330
Get stock_id:2881
Get stock_id:2892
Get stock_id:1101
Get stock_id:1102
Get stock_id:2454
Get stock_id:1216
Get stock_id:002608

,date,stock_id,StockExDividendTradingDate,CashExDividendTradingDate,CashDividendPaymentDate,TotalStock,TotalCash
0,2023-07-26,2881,,2023-07-20,2023-08-18,0.00000,1.500000
0,2023-07-26,1102,,2023-07-20,2023-08-17,0.00000,2.299588
0,2023-08-03,2884,2023-07-27,2023-07-27,2023-08-30,0.37877,0.189386
0,2023-08-11,1216,,2023-08-03,2023-09-08,0.00000,3.150000
0,2023-08-12,2891,,2023-08-04,2023-08-31,0.00000,1.000026

### 公開資訊操作
* [台灣證券交易所-除權除息計算結果表](https://www.twse.com.tw/zh/announcement/ex-right/twt49u.html)

* [證券櫃檯買賣中心OpenAPI-上櫃股票除權除息預告表](https://www.tpex.org.tw/openapi/#/)

#### 1.台灣證券交易所-除權除息計算結果表
> 參考網址格式  
https://www.twse.com.tw/rwd/zh/exRight/TWT49U?startDate=20230501&endDate=20230725&response=json&_=16902521  
https://www.twse.com.tw/rwd/zh/exRight/TWT49U?startDate=20230601&endDate=20230725&response=json&_=16902521

In [49]:
import datetime

def start_date_fun():
    # 輸入開始日期
    start_date_str = input("請輸入欲查詢起始日期，如20230101: ")
    # 將開始日期轉換為日期對象
    start_date = datetime.datetime.strptime(start_date_str, '%Y%m%d').date()

    # 輸入結束日期
    end_date_str = input("請輸入欲查詢結束日期，如20230110: ")
    # 將結束日期轉換為日期對象
    end_date = datetime.datetime.strptime(end_date_str, '%Y%m%d').date()

    # 計算日期區間
    days = (end_date - start_date).days

    print(f"查詢起日:{start_date_str}")
    print(f"查詢迄日:{end_date_str}")
    print(f"查詢區間:{days}天")

    return start_date_str, end_date_str, days

In [48]:
#台灣證券交易所-除權除息計算結果表[獲取一段區間之除權除息計算結果表]
start_date_str, end_date_str, days=start_date_fun()

#網址
url = f"https://www.twse.com.tw/rwd/zh/exRight/TWT49U?startDate={start_date_str}&endDate={end_date_str}&response=json&_=16902521"
response = requests.get(url)
data = response.json()

#轉成pandas

data = pd.DataFrame(data['data'])

# 更改欄位名稱
new_columns = ['日期', '股票代碼', '股票名稱', '除權息前收盤價', '除權息參考價', '權值+息值', '權/息', '漲停價', '跌停價', '開盤競價基準', '減除股利參考價', '詳細資料1', '詳細資料2', '最近一次申報每股 (單位)淨值', '最近一次申報每股 (單位)盈餘']
data.columns = new_columns

data

請輸入欲查詢起始日期，如20230101: 20230710
請輸入欲查詢結束日期，如20230110: 20230715
查詢起日:20230710
查詢迄日:20230715
查詢區間:5天

,日期,股票代碼,股票名稱,除權息前收盤價,除權息參考價,權值+息值,權/息,漲停價,跌停價,開盤競價基準,減除股利參考價,詳細資料1,詳細資料2,最近一次申報每股 (單位)淨值,最近一次申報每股 (單位)盈餘
0,112年07月10日,1234,黑松,40.85,39.05,1.800000,息,42.95,35.15,39.05,39.05,"1234,20230710",112年第1季(https://mops.twse.com.tw/mops/web/t163...,44.33,0.47
1,112年07月10日,1452,宏益,17.70,16.90,0.800000,息,18.55,15.25,16.90,16.90,"1452,20230710",112年第1季(https://mops.twse.com.tw/mops/web/t163...,19.70,-0.09
2,112年07月10日,1612,宏泰,26.60,25.10,1.500000,息,27.60,22.60,25.10,25.10,"1612,20230710",112年第1季(https://mops.twse.com.tw/mops/web/t163...,23.38,0.50
3,112年07月10日,2359,所羅門,37.30,35.80,1.500000,息,39.35,32.25,35.80,35.80,"2359,20230710",112年第1季(https://mops.twse.com.tw/mops/web/t163...,27.38,0.22
4,112年07月10日,2597,潤弘,119.00,109.00,10.000000,息,119.50,98.10,109.00,109.00,"2597,20230710",112年第1季(https://mops.twse.com.tw/mops/web/t163...,33.66,1.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,112年07月14日,3032,偉訓,69.40,67.38,2.017811,息,74.10,60.70,67.40,67.38,"3032,20230714",112年第1季(https://mops.twse.com.tw/mops/web/t163...,24.53,0.86
104,112年07月14日,4551,智伸科,149.50,143.50,6.000000,息,157.50,129.50,143.50,143.50,"4551,20230714",112年第1季(https://mops.twse.com.tw/mops/web/t163...,66.64,1.38
105,112年07月14日,4999,鑫禾,37.05,35.30,1.750000,息,38.80,31.80,35.30,35.30,"4999,20230714",112年第1季(https://mops.twse.com.tw/mops/web/t163...,45.50,-0.79
106,112年07月14日,5706,鳳凰,89.50,89.20,0.300000,息,98.10,80.30,89.20,89.20,"5706,20230714",112年第1季(https://mops.twse.com.tw/mops/web/t163...,17.14,-0.12
107,112年07月14日,6409,旭隼,"1,875.00","1,831.49",43.508924,息,"2,010.00","1,650.00","1,830.00","1,831.49","6409,20230714",112年第1季(https://mops.twse.com.tw/mops/web/t163...,105.17,8.55