<a href="https://colab.research.google.com/github/Sandwhaletree/Mai_Finlab/blob/main/%E5%A4%A7%E6%95%B8%E6%93%9A%E8%88%87%E9%87%91%E8%9E%8D%E8%82%A1%E7%A5%A8%E5%88%86%E6%9E%90/A01_%E8%82%A1%E7%A5%A8%E5%9B%9E%E6%B8%AC_DataFrame%E5%9F%BA%E7%A4%8E_0715.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# 定義list
a=[ [1,2,3],[2,3,4],[3,4,5] ]
# 從list 轉換成dataframe 的方法
pd.DataFrame(a)

   0  1  2
0  1  2  3
1  2  3  4
2  3  4  5

In [2]:
# 定義dictionary
b={    'open':[1,2,3],
       'high':[7,8,9],
       'close' :[3,4,5]}
# 從dictionary 轉換為dataframe 的方法
pd.DataFrame(b)

   open  high  close
0     1     7      3
1     2     8      4
2     3     9      5

In [3]:
# 組成函示庫
# function
# class
# 1- 屬性 (variable)
# 2- 方法 (function)

In [4]:
# 查看dataframe 屬性
a=pd.DataFrame(b)
a.ndim # 維度
a.shape # 面積
a.dtypes # 資料型態

open     int64
high     int64
close    int64
dtype: object

In [5]:
# 取得行數
a.shape[0]

3

In [6]:
# 如何呼叫欄位
a['open'] #老師習慣這種方法，因為有時候欄位是中文，用a.open感覺怪怪的
a.open

0    1
1    2
2    3
Name: open, dtype: int64

In [7]:
# 針對指定行數 去新增欄位
a['low']=[0,1,2] #資料筆數與原資料是一樣的
a

   open  high  close  low
0     1     7      3    0
1     2     8      4    1
2     3     9      5    2

In [8]:
# 直接將新欄位調整成統一值
a['volume']= 100
a

   open  high  close  low  volume
0     1     7      3    0     100
1     2     8      4    1     100
2     3     9      5    2     100

#### loc (locate)

In [9]:
# 如何取用資料-loc # locate
# a.loc[行,列] # 用欄位名稱來取得指定資料的方法
a.loc[1,'low']

1

In [10]:
#牛刀小試：抓到2的行 close的值
a.loc[2,'close']

5

In [11]:
# 抓到1,2兩行
a.loc[1:2,'open']

1    2
2    3
Name: open, dtype: int64

In [12]:
# 抓到值為1以後的行的值
a.loc[1:,'open']

1    2
2    3
Name: open, dtype: int64

In [13]:
#抓幾行的最高價
max(a.loc[1:2,'high'])

9

#### iloc(index locate)

In [14]:
# 如何取用資料-iloc # index locate
# 是用欄位索引來取得指定資料的方法
a.iloc[2,3] # 實際上取得low的值

2

In [15]:
# df的行索引
a.index

RangeIndex(start=0, stop=3, step=1)

In [16]:
# df的欄位索引
a.columns

Index(['open', 'high', 'close', 'low', 'volume'], dtype='object')

In [17]:
#列表推導式
[ i for i in a.index ]

[0, 1, 2]

In [18]:
#tmplist=[1,2,3]
#[ i for i in tmplist ]
#  ^     ^       ^
#運算式
#      迴圈變數 目標的集合

#[ 1, 2, 3 ] <- 集合
#(元素)
[ i for i in range(1,10) ]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
# dataframe 篩選資料
a[ a['high'] > 7 ]

   open  high  close  low  volume
1     2     8      4    1     100
2     3     9      5    2     100

In [20]:
# 取得 not 的條件判斷
a[ ~(a['high'] > 7) ]

   open  high  close  low  volume
0     1     7      3    0     100

In [21]:
# 複合判斷式
a[ (a['high'] > 7)&(a['open'] > 2) ]

   open  high  close  low  volume
2     3     9      5    2     100

### 改變路徑&讀取檔案

In [22]:
# 存檔讀檔
# 改變工作路徑[spyder]
import os
# os.chdir('C:\\Users\\jack\\Desktop\\生產力_課程筆記') #改變工作路徑
# os.chdir('C:\\Users\\USER\\OneDrive\\0_2023文件資料\\10_class_william_python stock\\課堂-生產力-202206')

In [23]:
#儲存csv檔案-含有原index
a.to_csv('範例dataframe.csv')
df=pd.read_csv('範例dataframe.csv')
df

   Unnamed: 0  open  high  close  low  volume
0           0     1     7      3    0     100
1           1     2     8      4    1     100
2           2     3     9      5    2     100

In [24]:
#儲存csv檔案-沒有原index->常用
a.to_csv('範例dataframe2.csv',index=False)
df=pd.read_csv('範例dataframe2.csv')
df

   open  high  close  low  volume
0     1     7      3    0     100
1     2     8      4    1     100
2     3     9      5    2     100

In [25]:
#儲存csv檔案-不儲存欄位名稱
a.to_csv('範例dataframe3.csv',
         index=False,
         header=False)
df=pd.read_csv('範例dataframe3.csv')
df

   1  7  3  0  100
0  2  8  4  1  100
1  3  9  5  2  100

In [26]:
#儲存csv檔案-欄位為中文名，csv下載打開會有中文亂碼
a['漲跌'] = 0
a.to_csv('範例dataframe4.csv')
df=pd.read_csv('範例dataframe4.csv')
df

   Unnamed: 0  open  high  close  low  volume  漲跌
0           0     1     7      3    0     100   0
1           1     2     8      4    1     100   0
2           2     3     9      5    2     100   0

In [27]:
#儲存csv檔案-欄位為中文名，csv下載打開會有中文亂碼->解決: windows編碼 cp950；mac編碼 utf-8
a['漲跌'] = 0
# a.to_csv('範例dataframe4-1.csv',encoding='cp950') #spyder環境下
a.to_csv('範例dataframe4-1.csv',encoding='utf-8')
df=pd.read_csv('範例dataframe4-1.csv')
df

   Unnamed: 0  open  high  close  low  volume  漲跌
0           0     1     7      3    0     100   0
1           1     2     8      4    1     100   0
2           2     3     9      5    2     100   0

In [28]:
#取多欄位表格
a['ma']=0
a[ ['open','ma'] ]

   open  ma
0     1   0
1     2   0
2     3   0

In [29]:
#欄位自行重新排序
#a.columns
a[ ['open', 'high', 'ma', '漲跌' , 'close', 'low',
    'volume'] ].to_csv('範例dataframe5.csv',encoding='utf-8')
df=pd.read_csv('範例dataframe5.csv',encoding='utf-8')
df

   Unnamed: 0  open  high  ma  漲跌  close  low  volume
0           0     1     7   0   0      3    0     100
1           1     2     8   0   0      4    1     100
2           2     3     9   0   0      5    2     100

### API套件-公開資料免費
* yfinance - 國外股市資訊豐富
* finmind - 國內的金融商品公開資訊

In [30]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.25)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.22.4)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.27.1)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2022.7.1)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.3.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.11.2)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26->yfinance) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26->yfinance) (3.4)

In [31]:
import yfinance as yf
data=yf.Ticker('BABA') #台灣股票 #'0050.TW'
data

yfinance.Ticker object <BABA>

In [32]:
data.info #data的屬性

{'address1': '969 West Wen Yi Road',
 'address2': 'Yu Hang District',
 'city': 'Hangzhou',
 'zip': '311121',
 'country': 'China',
 'phone': '86 571 8502 2088',
 'fax': '86 571 8376 8429',
 'website': 'https://www.alibabagroup.com',
 'industry': 'Internet Retail',
 'industryDisp': 'Internet Retail',
 'sector': 'Consumer Cyclical',
 'longBusinessSummary': "Alibaba Group Holding Limited, through its subsidiaries, provides technology infrastructure and marketing reach to help merchants, brands, retailers, and other businesses to engage with their users and customers in the People's Republic of China and internationally. The company operates through seven segments: China Commerce, International Commerce, Local Consumer Services, Cainiao, Cloud, Digital Media and Entertainment, and Innovation Initiatives and Others. It operates Taobao, a digital retail platform; Tmall, a third-party online and mobile commerce platform; Alimama, a monetization platform; 1688.com and Alibaba.com, which are online wholesale marketplaces; AliExpress, a retail marketplace; Lazada, Trendyol, and Daraz that are e-commerce platforms; Freshippo, a retail platform for groceries and fresh goods; and Tmall Global, an import e-commerce platform. The company also operates Cainiao Network logistic services platform; Ele.me, an on-demand delivery and local services platform; Koubei, a restaurant and local services guide platform; and Fliggy, an online travel platform. In addition, it offers pay-for-performance, in-feed, and display marketing services; and Taobao Ad Network and Exchange, a real-time online bidding marketing exchange. Further, the company provides elastic computing, storage, network, security, database, big data, and IoT services; and hardware, software license, software installation, and application development and maintenance services. Additionally, it operates Youku, an online video platform; Quark, a platform for information search, storage, and consumption; Alibaba Pictures and other content platforms that provide online videos, films, live events, news feeds, literature, music, and others; Amap, a mobile digital map, navigation, and real-time traffic information app; DingTalk, a business efficiency mobile app; and Tmall Genie smart speaker. The company was incorporated in 1999 and is based in Hangzhou, the People's Republic of China.",
 'fullTimeEmployees': 235216,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Joseph C.  Tsai',
   'age': 58,
   'title': 'Exec. Vice Chairman',
   'yearBorn': 1964,
   'fiscalYear': 2018,
   'totalPay': 0,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Yong  Zhang',
   'age': 50,
   'title': 'CEO & Exec. Chairman',
   'yearBorn': 1972,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. J. Michael  Evans',
   'age': 64,
   'title': 'Pres & Director',
   'yearBorn': 1958,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hong  Xu',
   'age': 49,
   'title': 'Chief Financial Officer',
   'yearBorn': 1973,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Joan  Zhou',
   'title': 'Investment Director',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Yuen Jen Yao',
   'title': 'Sr. VP & Head of Corp. Fin.',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Robert  Lin',
   'title': 'Investor Relations',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Siying  Yu',
   'age': 48,
   'title': 'Gen. Counsel',
   'yearBorn': 1974,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Wenhong  Tong',
   'age': 52,
   'title': 'Chief People Officer',
   'yearBorn': 1970,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Xiaofeng  Shao',
   'age': 56,
   'title': 'Sr. VP of Ant Group',
   'yearBorn': 1966,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'compensationAsOfEpochDate': 1546214400,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 95.44,
 'open': 97.75,
 'dayLow': 97.96,
 'dayHigh': 101.22,
 'regularMarketPreviousClose': 95.44,
 'regularMarketOpen': 97.75,
 'regularMarketDayLow': 97.96,
 'regularMarketDayHigh': 101.22,
 'payoutRatio': 0.0,
 'beta': 0.647882,
 'trailingPE': 25.981915,
 'forwardPE': 10.561975,
 'volume': 31331804,
 'regularMarketVolume': 31331804,
 'averageVolume': 19470185,
 'averageVolume10days': 20900920,
 'averageDailyVolume10Day': 20900920,
 'bid': 101.0,
 'ask': 101.5,
 'bidSize': 1100,
 'askSize': 2200,
 'marketCap': 257659387904,
 'fiftyTwoWeekLow': 58.01,
 'fiftyTwoWeekHigh': 121.3,
 'priceToSalesTrailing12Months': 0.29660785,
 'fiftyDayAverage': 87.9404,
 'twoHundredDayAverage': 89.33075,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'enterpriseValue': 49448251392,
 'profitMargins': 0.08379,
 'floatShares': 2077572500,
 'sharesOutstanding': 2562500096,
 'sharesShort': 57922186,
 'sharesShortPriorMonth': 58833443,
 'sharesShortPreviousMonthDate': 1686787200,
 'dateShortInterest': 1689292800,
 'sharesPercentSharesOut': 0.0227,
 'heldPercentInsiders': 7e-05,
 'heldPercentInstitutions': 0.14895001,
 'shortRatio': 3.06,
 'impliedSharesOutstanding': 0,
 'bookValue': 386.208,
 'priceToBook': 0.26035193,
 'lastFiscalYearEnd': 1680220800,
 'nextFiscalYearEnd': 1711843200,
 'mostRecentQuarter': 1680220800,
 'netIncomeToCommon': 72508997632,
 'trailingEps': 3.87,
 'forwardEps': 9.52,
 'pegRatio': 71.19,
 'enterpriseToRevenue': 0.057,
 'enterpriseToEbitda': 0.343,
 '52WeekChange': 11.301744,
 'SandP52WeekChange': 11.25617,
 'exchange': 'NYQ',
 'quoteType': 'EQUITY',
 'symbol': 'BABA',
 'underlyingSymbol': 'BABA',
 'shortName': 'Alibaba Group Holding Limited',
 'longName': 'Alibaba Group Holding Limited',
 'firstTradeDateEpochUtc': 1411133400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '8d2bbbd9-9979-370d-8c45-f5246fdce510',
 'messageBoardId': 'finmb_42083601',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 100.55,
 'targetHighPrice': 182.13,
 'targetLowPrice': 91.57,
 'targetMeanPrice': 136.48,
 'targetMedianPrice': 139.34,
 'recommendationMean': 1.8,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 43,
 'totalCash': 524469993472,
 'totalCashPerShare': 204.671,
 'ebitda': 144367992832,
 'totalDebt': 191733006336,
 'quickRatio': 1.361,
 'currentRatio': 1.811,
 'totalRevenue': 868687020032,
 'debtToEquity': 17.074,
 'revenuePerShare': 331.244,
 'returnOnAssets': 0.03736,
 'returnOnEquity': 0.05947,
 'freeCashflow': 111610871808,
 'operatingCashflow': 199752007680,
 'revenueGrowth': 0.02,
 'grossMargins': 0.36721,
 'ebitdaMargins': 0.16619,
 'operatingMargins': 0.118640006,
 'financialCurrency': 'CNY',
 'trailingPegRatio': 1.0559}

In [33]:
data2=data.financials # 連續四年損益表
data2

,2023-03-31,2022-03-31,2021-03-31,2020-03-31
Tax Effect Of Unusual Items,-461380000.0,-10056400000.0,0.0,-69120000.0
Tax Rate For Calcs,0.17,0.4,0.18,0.12
Normalized EBITDA,122392000000.0,116949000000.0,182481000000.0,185789000000.0
Total Unusual Items,-2714000000.0,-25141000000.0,0.0,-576000000.0
Total Unusual Items Excluding Goodwill,-2714000000.0,-25141000000.0,0.0,-576000000.0
Net Income From Continuing Operation Net Minority Interest,72783000000.0,62249000000.0,150578000000.0,149433000000.0
Reconciled Depreciation,13504000000.0,11647000000.0,12427000000.0,13388000000.0
Reconciled Cost Of Revenue,549695000000.0,539450000000.0,421205000000.0,282367000000.0
EBIT,106174000000.0,80161000000.0,170054000000.0,171825000000.0
Net Interest Income,-16989000000.0,-20611000000.0,68318000000.0,67776000000.0
Interest Expense,16989000000.0,20611000000.0,4476000000.0,5180000000.0
Interest Income,NaN,NaN,72794000000.0,72956000000.0
Normalized Income,75035620000.0,77333600000.0,150578000000.0,149939880000.0
Net Income From Continuing And Discontinued Operation,72783000000.0,62249000000.0,150578000000.0,149433000000.0
Total Expenses,765622000000.0,758283000000.0,627611000000.0,417705000000.0
Total Operating Income As Reported,100351000000.0,69638000000.0,89678000000.0,91430000000.0
Diluted Average Shares,NaN,2723375000.0,2747750000.0,2668250000.0
Basic Average Shares,NaN,2694750000.0,2702375000.0,2627125000.0
Diluted EPS,NaN,22.72,54.72,55.92
Basic EPS,NaN,22.96,55.620704,56.8
Diluted NI Availto Com Stockholders,72509000000.0,61959000000.0,150308000000.0,149215000000.0
Average Dilution Earnings,-38000000.0,-37000000.0,-55000000.0,-48000000.0
Net Income Common Stockholders,72509000000.0,61959000000.0,150308000000.0,149263000000.0
Otherunder Preferred Stock Dividend,274000000.0,290000000.0,270000000.0,170000000.0
Net Income,72783000000.0,62249000000.0,150578000000.0,149433000000.0
Minority Interests,7210000000.0,15170000000.0,7294000000.0,9083000000.0
Net Income Including Noncontrolling Interests,65573000000.0,47079000000.0,143284000000.0,140350000000.0
Net Income Continuous Operations,65573000000.0,47079000000.0,143284000000.0,140350000000.0
Earnings From Equity Interest Net Of Tax,-8063000000.0,14344000000.0,6984000000.0,-5733000000.0
Tax Provision,15549000000.0,26815000000.0,29278000000.0,20562000000.0
Pretax Income,89185000000.0,59550000000.0,165578000000.0,166645000000.0
Other Income Expense,3109000000.0,-14618000000.0,7582000000.0,6863000000.0
Other Non Operating Income Expenses,5823000000.0,10523000000.0,7582000000.0,7439000000.0
Special Income Charges,-2714000000.0,-25141000000.0,0.0,-576000000.0
Other Special Charges,NaN,NaN,NaN,-3835000000.0
Impairment Of Capital Assets,2714000000.0,25141000000.0,0.0,576000000.0
Restructuring And Mergern Acquisition,NaN,NaN,NaN,97000000.0
Gain On Sale Of Security,NaN,NaN,NaN,-514000000.0
Net Non Operating Interest Income Expense,-16989000000.0,-20611000000.0,68318000000.0,67776000000.0
Interest Expense Non Operating,16989000000.0,20611000000.0,4476000000.0,5180000000.0
Interest Income Non Operating,NaN,NaN,72794000000.0,72956000000.0
Operating Income,103065000000.0,94779000000.0,89678000000.0,92006000000.0
Operating Expense,215927000000.0,218833000000.0,206406000000.0,135338000000.0
Other Operating Expenses,NaN,NaN,NaN,-998000000.0
Depreciation Amortization Depletion Income Statement,13504000000.0,11647000000.0,12427000000.0,13388000000.0
Depreciation And Amortization In Income Statement,13504000000.0,11647000000.0,12427000000.0,13388000000.0
Amortization,13504000000.0,11647000000.0,12427000000.0,13388000000.0
Amortization Of Intangibles Income Statement,13504000000.0,11647000000.0,12427000000.0,13388000000.0
Research And Development,56744000000.0,55465000000.0,57236000000.0,43080000000.0
Selling General And Administration,145679000000.0,151721000000.0,136743000000.0,78870000000.0
Selling And Marketing Expense,103496000000.0,119799000000.0,81519000000.0,50673000000.0
General And Administrative Expense,42183000000.0,31922000000.0,55224000000.0,28197000000.0
Other Gand A,42183000000.0,31922000000.0,55224000000.0,28197000000.0
Gross Profit,318992000000.0,313612000000.0,296084000000.0,227344000000.0
Cost Of Revenue,549695000000.0,539450000000.0,421205000000.0,282367000000.0
Total Revenue,868687000000.0,853062000000.0,717289000000.0,509711000000.0
Operating Revenue,868687000000.0,853062000000.0,717289000000.0,509711000000.0

In [34]:
#作者尚未將功能建立好
# data.earnings

In [35]:
data4=data.actions
data4

Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []

In [36]:
data.history() # 取得歷史資料

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-06-29 00:00:00-04:00,83.389999,83.989998,83.000000,83.550003,13362500,0.0,0.0
2023-06-30 00:00:00-04:00,83.230003,84.230003,83.010002,83.349998,12154300,0.0,0.0
2023-07-03 00:00:00-04:00,84.870003,85.635002,84.000000,84.070000,11514400,0.0,0.0
2023-07-05 00:00:00-04:00,83.980003,84.690002,82.820000,84.300003,11203900,0.0,0.0
2023-07-06 00:00:00-04:00,83.120003,83.949997,82.639999,83.839996,12930300,0.0,0.0
2023-07-07 00:00:00-04:00,86.760002,91.570000,86.629997,90.550003,46815900,0.0,0.0
2023-07-10 00:00:00-04:00,90.050003,92.040001,89.599998,90.559998,25401800,0.0,0.0
2023-07-11 00:00:00-04:00,91.019997,92.320000,89.010002,91.790001,20768800,0.0,0.0
2023-07-12 00:00:00-04:00,94.110001,95.029999,92.550003,94.000000,24161400,0.0,0.0
2023-07-13 00:00:00-04:00,95.029999,97.004997,94.599998,96.610001,24021400,0.0,0.0
2023-07-14 00:00:00-04:00,95.220001,96.089996,94.239998,94.559998,18870000,0.0,0.0
2023-07-17 00:00:00-04:00,92.250000,93.550003,91.040001,93.410004,17317300,0.0,0.0
2023-07-18 00:00:00-04:00,91.540001,92.209999,90.150002,91.199997,20249700,0.0,0.0
2023-07-19 00:00:00-04:00,93.570000,94.709999,92.089996,92.089996,17228100,0.0,0.0
2023-07-20 00:00:00-04:00,91.690002,93.120003,91.349998,91.900002,14753000,0.0,0.0
2023-07-21 00:00:00-04:00,92.889999,93.230003,91.540001,92.169998,13882900,0.0,0.0
2023-07-24 00:00:00-04:00,92.070000,97.469002,91.300003,96.349998,33376100,0.0,0.0
2023-07-25 00:00:00-04:00,98.169998,98.489998,94.610001,94.980003,25827300,0.0,0.0
2023-07-26 00:00:00-04:00,94.949997,97.544998,94.839996,97.139999,15833400,0.0,0.0
2023-07-27 00:00:00-04:00,97.750000,97.989998,95.161003,95.440002,18685500,0.0,0.0
2023-07-28 00:00:00-04:00,98.070000,101.220001,97.959999,100.550003,31855900,0.0,0.0

In [37]:
# 透過yahoo finance 去下載股票日頻率資料
data=yf.download('BABA',
                 start = '2022-01-1',
                 end ='2022-07-15' )
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-01-03,119.379997,121.949997,115.820000,120.379997,120.379997,16775300
2022-01-04,119.529999,120.870003,115.769997,119.559998,119.559998,20824000
2022-01-05,118.000000,126.620003,117.699997,121.160004,121.160004,36651100
2022-01-06,124.260002,128.399994,123.464996,126.629997,126.629997,32045800
2022-01-07,130.240005,133.880005,128.179993,129.809998,129.809998,38113000
...,...,...,...,...,...,...
2022-07-08,122.260002,125.839996,120.699997,120.900002,120.900002,27221400
2022-07-11,115.459999,115.580002,109.330002,109.570000,109.570000,31249900
2022-07-12,110.860001,111.000000,107.059998,109.209999,109.209999,22318500
2022-07-13,106.839996,110.639999,106.750000,109.099998,109.099998,16861400
2022-07-14,107.800003,108.540001,100.709999,103.760002,103.760002,35314900

In [38]:
data=yf.download('0050.TW',
                 start = '2022-01-1',
                 end ='2022-07-15' )
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-01-03,146.000000,147.350006,146.000000,146.399994,146.399994,6784202
2022-01-04,147.699997,149.600006,147.699997,149.600006,149.600006,9634440
2022-01-05,150.100006,150.550003,149.100006,149.300003,149.300003,11406601
2022-01-06,148.300003,148.750000,147.000000,147.899994,147.899994,8621233
2022-01-07,148.300003,149.000000,146.500000,146.600006,146.600006,6989124
...,...,...,...,...,...,...
2022-07-08,113.300003,113.900002,112.300003,113.250000,113.250000,10177857
2022-07-11,113.650002,113.699997,111.849998,112.250000,112.250000,7572953
2022-07-12,110.949997,110.949997,109.150002,109.550003,109.550003,11133444
2022-07-13,113.000000,113.650002,112.599998,113.449997,113.449997,24824897
2022-07-14,112.699997,114.250000,111.800003,114.000000,114.000000,14750428

In [39]:
#僅7天不構成歷史回測時間長度，故不使用下方時間區間
data=yf.download('0050.TW',
                 period = '7d',
                 interval= '1m')
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2023-07-20 09:00:00+08:00,129.050003,129.149994,129.050003,129.100006,129.100006,0
2023-07-20 09:01:00+08:00,129.100006,129.100006,129.050003,129.050003,129.050003,15000
2023-07-20 09:02:00+08:00,129.050003,129.100006,129.050003,129.050003,129.050003,42000
2023-07-20 09:03:00+08:00,129.050003,129.149994,129.000000,129.149994,129.149994,32000
2023-07-20 09:04:00+08:00,129.149994,129.199997,129.149994,129.199997,129.199997,10000
...,...,...,...,...,...,...
2023-07-28 13:20:00+08:00,129.350006,129.350006,129.350006,129.350006,129.350006,1924
2023-07-28 13:21:00+08:00,129.350006,129.350006,129.350006,129.350006,129.350006,2872
2023-07-28 13:22:00+08:00,129.350006,129.350006,129.350006,129.350006,129.350006,5030
2023-07-28 13:23:00+08:00,129.350006,129.350006,129.350006,129.350006,129.350006,3017
2023-07-28 13:24:00+08:00,129.399994,129.399994,129.350006,129.399994,129.399994,31166

In [40]:
#下載周資料 月資料
data=yf.download('0050.TW',
                 start = '2022-01-1',
                 end ='2022-07-15' ,
                 interval='1wk')
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-01-03,146.000000,150.550003,146.000000,146.600006,146.600006,43435600
2022-01-10,146.000000,151.199997,145.399994,150.300003,150.300003,61176800
2022-01-17,151.100006,152.399994,142.300003,142.649994,142.649994,82148142
2022-01-24,142.100006,144.000000,141.050003,141.550003,141.550003,54933257
2022-01-31,141.550003,141.550003,141.550003,141.550003,141.550003,0
2022-02-07,142.600006,145.050003,141.199997,144.949997,144.949997,53487710
2022-02-14,143.949997,145.000000,141.949997,144.100006,144.100006,34733325
2022-02-21,143.449997,143.850006,137.850006,138.500000,138.500000,79660667
2022-02-28,138.500000,140.800003,137.949997,138.449997,138.449997,31408714
2022-03-07,136.899994,136.899994,131.000000,134.399994,134.399994,139788230
2022-03-14,135.000000,136.600006,131.100006,136.100006,136.100006,77752742
2022-03-21,136.800003,138.500000,136.300003,138.199997,138.199997,33185746
2022-03-28,137.000000,138.699997,135.550003,136.949997,136.949997,36374392
2022-04-04,136.949997,136.949997,133.750000,134.550003,134.550003,35252998
2022-04-11,134.149994,135.750000,131.600006,132.250000,132.250000,63615381
2022-04-18,132.000000,133.600006,130.850006,131.600006,131.600006,48968096
2022-04-25,130.000000,130.050003,125.949997,128.750000,128.750000,93739158
2022-05-02,128.750000,129.800003,125.949997,126.650002,126.650002,39457449
2022-05-09,125.500000,125.550003,121.199997,122.349998,122.349998,53789657
2022-05-16,123.449997,126.000000,122.500000,124.650002,124.650002,27132114
2022-05-23,125.300003,125.800003,122.849998,125.500000,125.500000,27821014
2022-05-30,127.250000,130.050003,127.050003,127.800003,127.800003,32404632
2022-06-06,128.250000,129.100006,126.400002,127.099998,127.099998,19025193
2022-06-13,124.099998,125.000000,120.400002,120.849998,120.849998,70044359
2022-06-20,120.900002,122.199997,117.250000,118.150002,118.150002,59797221
2022-06-27,119.800003,121.449997,111.199997,111.550003,111.550003,88911215
2022-07-04,111.250000,113.900002,108.449997,113.250000,113.250000,81880198
2022-07-11,113.650002,115.650002,109.150002,115.500000,115.500000,76837034

#### 將取資料寫成函數 Data.py

In [41]:
# 將取資料寫成函數 Data.py
import yfinance as yf
import pandas as pd
import os

#定義變數
#prod='0050.TW'
#starday='2022-01-1'
#endday='2022-07-15'

def getDataYF(prod,starday,endday):
    #定義存檔名稱
    backup_file='data\\YF_%s_%s_%s.csv'%(prod,starday,endday)

    #第一步:确認是否有本地端檔案
    if not os.path.exists(backup_file):
        #如果沒有我就跟之後寫
        data=yf.download(prod,start = starday, end =endday)
        data.to_csv(backup_file)
        print(f'新增{backup_file}檔案')

    #如果有我就用本地端檔案即可
    else:
        data=pd.read_csv(backup_file)
        #檔案取得後，須將時間改成索引
        data=data.set_index('Date')
        print(f'本地端已有{backup_file}檔案')
    return data

#df=getDataYF(prod,starday,endday)

In [42]:
# 時間的處理
import datetime

# 取得 '2022-01-01' 的後面 10天的日期 **
# 字串轉時間 時間+10天 時間轉回去字串
# 字串轉時間
sd='2022-01-01'
sd1=datetime.datetime.strptime(sd,'%Y-%m-%d')
sd1

datetime.datetime(2022, 1, 1, 0, 0)

In [43]:
# %Y YYYY %m mm %d dd
# 時間轉字串
sd1.strftime('%Y%m%d')

'20220101'

In [44]:
# 時間的運算 timedelta(日,秒)
sd1+datetime.timedelta(10)
sd1-datetime.timedelta(10)

datetime.datetime(2021, 12, 22, 0, 0)

In [45]:
#日期轉字串
( sd1+datetime.timedelta(10) ).strftime('%Y%m%d')

'20220111'

In [46]:
#加秒數
sd1+datetime.timedelta(10,10)

datetime.datetime(2022, 1, 11, 0, 0, 10)

In [47]:
# 時間的判斷
sd2=sd1+datetime.timedelta(10)
sd1 > sd2
sd1 < sd2

True

#### finmind
* https://finmind.github.io/
  * 台灣還原股價資料表 TaiwanStockPriceAdj
* https://finmindtrade.com/