<a href="https://colab.research.google.com/github/Sandwhaletree/Mai_Finlab/blob/main/%E8%82%A1%E7%A5%A8%E8%B2%A1%E5%8B%99%E5%88%86%E6%9E%90/A02_Crawing_publicinfo_%E5%85%AC%E5%8F%B8%E8%B2%A1%E5%8B%99%E5%A0%B1%E8%A1%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **👉快速查詢1)sii上市 2)otc上櫃 3)rotc興櫃 4)pub公開發行公司之財務報表**
  * 1)損益表
  * 2)資產負債表
  * 3)現金流量表
  * 4)營業分析表

In [1]:
import requests
import pandas as pd
import datetime

In [31]:
#設計函數financial_statement(market,year, season)
def financial_statement(market, year, season):
    res = requests.post(url, {
                            'encodeURIComponent':1,
                            'step':1,
                            'firstin':1,
                            'off':1,
                            'TYPEK': market,
                            'year':str(year),
                            'season':str(season),
                           })
    #把資料分別儲存至空變數中
    if market == "sii" or market == "rotc" or market == "pub" :
      if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表
        df = pd.read_html(res.text)[3] #df[0]=表頭；[1]=銀行；[2]=證券；[3]=一般；[4]=金控；[5]=保險；[6]=異業
        print(f'{market}:[3]=一般')
      else:   #4)營業分析表
        df = pd.read_html(res.text)[2]
    else:
      if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表
        df = pd.read_html(res.text)[2] #df[0]=表頭；#[1]=證券；[2]=一般
        print(f'otc:[2]=一般')
      else:   #4)營業分析表
          df = pd.read_html(res.text)[2]

    df.insert(1,'年度', year)
    df.insert(2,'季別', season)

    df.columns = df.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt= df[df['公司代號'] != '公司代號'] #濾掉重複之表頭
    filt.set_index('公司名稱', inplace=True)
    return filt

In [32]:
#市場 #market
market = int(input('請輸入欲查詢之市場數字-1)sii上市 2)otc上櫃 3)rotc興櫃 4)pub公開發行: '))
if market == 1:
    market = 'sii'
elif market == 2 :
    market = 'otc'
elif market == 3 :
    market = 'rotc'
elif market == 4 : #營業分析表
    market = 'pub'
else:
    print('type does not match')


#年度
year = int(input('請輸入欲查詢年份: '))
if year >= 1000:
    year -= 1911

#2.財報類型 #type
type = int(input('請輸入欲查詢之表格數字-1)損益表 2)資產負債表 3)現金流量表 4)營業分析表: '))

if type == 1: #損益表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb04'
elif type == 2 : #資產負債表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb05'
elif type == 3 : #現金流量表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb20'
elif type == 4 : #營業分析表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb06'
else:
    print('type does not match')

#3.季節 #season
season = int(input('請輸入欲查詢之季節:'))

df = financial_statement(market, year, season)
df

請輸入欲查詢之市場數字-1)sii上市 2)otc上櫃 3)rotc興櫃 4)pub公開發行: 2
請輸入欲查詢年份: 2022
請輸入欲查詢之表格數字-1)損益表 2)資產負債表 3)現金流量表 4)營業分析表: 2
請輸入欲查詢之季節:4
otc:[2]=一般

,公司代號,年度,季別,流動資產,非流動資產,資產總計,流動負債,非流動負債,負債總計,股本,...,庫藏股票,歸屬於母公司業主之權益合計,共同控制下前手權益,合併前非屬共同控制股權,非控制權益,權益總計,待註銷股本股數（單位：股）,預收股款（權益項下）之約當發行股數（單位：股）,母公司暨子公司所持有之母公司庫藏股股數（單位：股）,每股參考淨值
公司名稱,,,,,,,,,,,,,,,,,,,,,
茂生農經,1240,111,4,1331989,882265,2214254,864563,31939,896502,385982,...,--,1230443,--,--,87309,1317752,--,0,0,31.88
安心,1259,111,4,1972271,3352068,5324339,1713760,1605033,3318793,323895,...,0,1984924,--,--,20622,2005546,0,0,0,61.28
德麥,1264,111,4,2935176,1771441,4706617,989079,76306,1065385,370644,...,-2432,2934302,--,--,706930,3641232,0,0,12000,79.19
漢來美食,1268,111,4,2162752,4118476,6281228,1569438,2861335,4430773,427237,...,-65810,1850455,--,--,--,1850455,--,0,500000,43.83
台翰,1336,111,4,1503475,1270008,2773483,663872,386076,1049948,788184,...,--,1723535,--,--,--,1723535,0,0,0,21.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
琉園,9949,111,4,280503,191489,471992,46067,21395,67462,440334,...,0,404530,--,--,0,404530,0,0,0,9.19
萬國通,9950,111,4,1281216,3069267,4350483,1873692,2153130,4026822,1677160,...,--,300195,--,--,23466,323661,--,0,0,1.79
皇田,9951,111,4,3935919,1725458,5661377,1999810,287232,2287042,749000,...,--,3374335,--,--,--,3374335,0,0,0,45.05
邁達康,9960,111,4,858926,429920,1288846,535895,150004,685899,335925,...,0,602947,--,--,0,602947,0,0,0,17.95
有益,9962,111,4,1178795,315877,1494672,279927,11895,291822,902203,...,--,1202850,--,--,0,1202850,--,0,0,13.33

#### 設計關鍵

In [3]:
#1)使用者版面設計-輸入關鍵字

#市場 #market
market = int(input('請輸入欲查詢之市場數字-1)sii上市 2)otc上櫃 3)rotc興櫃 4)pub公開發行: '))
if market == 1:
    market = 'sii'
elif market == 2 :
    market = 'otc'
elif market == 3 :
    market = 'rotc'
elif market == 4 : #營業分析表
    market = 'pub'
else:
    print('type does not match')

#財報類型 #type
type = int(input('請輸入欲查詢之表格數字-1)損益表 2)資產負債表 3)現金流量表 4)營業分析表: '))
if type == 1: #損益表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb04'
elif type == 2 : #資產負債表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb05'
elif type == 3 : #現金流量表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb20'
elif type == 4 : #營業分析表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb06'
else:
    print('type does not match')

#年份 #year
year = int(input('請輸入欲查詢年份: '))
if year >= 1000:
    year -= 1911

#季節 #season
season = input('請輸入欲查詢之季節:')

請輸入欲查詢之市場數字-1)sii上市 2)otc上櫃 3)rotc興櫃 4)pub公開發行: 1
請輸入欲查詢之表格數字-1)損益表 2)資產負債表 3)現金流量表 4)營業分析表: 1
請輸入欲查詢年份: 2022
請輸入欲查詢之季節:4

In [9]:
#2)爬蟲財報內容

#網站連結

res = requests.post(url, {
                        'encodeURIComponent':1,
                        'step':1,
                        'firstin':1,
                        'off':1,
                        'TYPEK': market,            #input market(str)
                        'year':str(year),           #input market(str)
                        'season':str(season),
                        })
#把資料分別儲存至空變數中
if market == "sii" :
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表 #[0]表頭
    df_bank = pd.read_html(res.text)[1]      #[1]=銀行
    df_sec = pd.read_html(res.text)[2]       #[2]=證券
    df_normal = pd.read_html(res.text)[3]    #[3]=一般
    df_fh = pd.read_html(res.text)[4]        #[4]=金控
    df_ins = pd.read_html(res.text)[5]       #[5]=保險
    df_rare = pd.read_html(res.text)[6]      #[6]=異業
  else: #4)營業分析表
    df_all = pd.read_html(res.text)[0]  #[0]=全部行業；[1]=附註
    df_all.columns = df_all.iloc[0]
    df_all.columns = df_all.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt_all= df_all[df_all['公司代號'] != '公司代號'] #濾掉重複之表頭

elif market == "otc" :
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表 [0]表頭
    df_sec = pd.read_html(res.text)[1]  #[1]=證券
    df_normal = pd.read_html(res.text)[2]  #[2]=一般
  else: #4)營業分析表
    df_all = pd.read_html(res.text)[0]  #[0]=全部行業；[1]=附註
    df_all.columns = df_all.iloc[0]
    df_all.columns = df_all.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt_all= df_all[df_all['公司代號'] != '公司代號'] #濾掉重複之表頭

elif market == "rotc" :
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表 #[0]=表頭
    df_bank = pd.read_html(res.text)[1]      #[1]=銀行
    df_sec = pd.read_html(res.text)[2]      #[2]=證券
    df_normal = pd.read_html(res.text)[3]      #[3]=一般
    df_ins = pd.read_html(res.text)[4]      #[4]=保險
  else: #4)營業分析表
    df_all = pd.read_html(res.text)[0]  #[0]=全部行業；[1]=附註
    df_all.columns = df_all.iloc[0]
    df_all.columns = df_all.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt_all= df_all[df_all['公司代號'] != '公司代號'] #濾掉重複之表頭
else:
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表
    df_bank = pd.read_html(res.text)[1]  #[1]=銀行
    df_sec = pd.read_html(res.text)[2]  #[2]=證券
    df_normal = pd.read_html(res.text)[3]  #[3]=一般
    df_fh = pd.read_html(res.text)[4]  #[4]=金控
    df_ins = pd.read_html(res.text)[5]  #[5]=保險
  else: #4)營業分析表
    df_all = pd.read_html(res.text)[0]  #[0]=全部行業；[1]=附註
    df_all.columns = df_all.iloc[0]
    df_all.columns = df_all.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt_all= df_all[df_all['公司代號'] != '公司代號'] #濾掉重複之表頭

#### 原始爬蟲表格檢查

In [33]:
res = requests.post(url, {
                        'encodeURIComponent':1,
                        'step':1,
                        'firstin':1,
                        'off':1,
                        'TYPEK': market,
                        'year':str(year),
                        'season':str(season),
                        })
#把資料分別儲存至空變數中
if market == "sii" or market == "rotc" or market == "pub" :
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表
    df = pd.read_html(res.text)[3] #df[0]=表頭；[1]=銀行；[2]=證券；[3]=一般；[4]=金控；[5]=保險；[6]=異業
  else:   #4)營業分析表
    df = pd.read_html(res.text)[2]
else:
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表
    df = pd.read_html(res.text)[2] #df[0]=表頭；#[1]=證券；[2]=一般
  else:   #4)營業分析表
      df = pd.read_html(res.text)[2]

df.insert(1,'年度', year)
df.insert(2,'季別', season)

#不同財報選取表格不同

# #1)損益表 2)資產負債表 3)現金流量表
# if type == 1 or type == 2 or type == 3:
#   df = pd.read_html(res.text)[2] #df[0]=表頭；[1]=銀行；[2]=證券；[3]=一般；[4]=金控；[5]=保險；[6]=異業
# #4)營業分析表
# else:
#   df = pd.read_html(res.text)[2]

df.columns = df.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
filt= df[df['公司代號'] != '公司代號'] #濾掉重複之表頭
filt.set_index('公司名稱', inplace=True)

In [34]:
filt

,公司代號,年度,季別,流動資產,非流動資產,資產總計,流動負債,非流動負債,負債總計,股本,...,庫藏股票,歸屬於母公司業主之權益合計,共同控制下前手權益,合併前非屬共同控制股權,非控制權益,權益總計,待註銷股本股數（單位：股）,預收股款（權益項下）之約當發行股數（單位：股）,母公司暨子公司所持有之母公司庫藏股股數（單位：股）,每股參考淨值
公司名稱,,,,,,,,,,,,,,,,,,,,,
茂生農經,1240,111,4,1331989,882265,2214254,864563,31939,896502,385982,...,--,1230443,--,--,87309,1317752,--,0,0,31.88
安心,1259,111,4,1972271,3352068,5324339,1713760,1605033,3318793,323895,...,0,1984924,--,--,20622,2005546,0,0,0,61.28
德麥,1264,111,4,2935176,1771441,4706617,989079,76306,1065385,370644,...,-2432,2934302,--,--,706930,3641232,0,0,12000,79.19
漢來美食,1268,111,4,2162752,4118476,6281228,1569438,2861335,4430773,427237,...,-65810,1850455,--,--,--,1850455,--,0,500000,43.83
台翰,1336,111,4,1503475,1270008,2773483,663872,386076,1049948,788184,...,--,1723535,--,--,--,1723535,0,0,0,21.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
琉園,9949,111,4,280503,191489,471992,46067,21395,67462,440334,...,0,404530,--,--,0,404530,0,0,0,9.19
萬國通,9950,111,4,1281216,3069267,4350483,1873692,2153130,4026822,1677160,...,--,300195,--,--,23466,323661,--,0,0,1.79
皇田,9951,111,4,3935919,1725458,5661377,1999810,287232,2287042,749000,...,--,3374335,--,--,--,3374335,0,0,0,45.05
邁達康,9960,111,4,858926,429920,1288846,535895,150004,685899,335925,...,0,602947,--,--,0,602947,0,0,0,17.95
有益,9962,111,4,1178795,315877,1494672,279927,11895,291822,902203,...,--,1202850,--,--,0,1202850,--,0,0,13.33

In [18]:
#市場 #market
market = int(input('請輸入欲查詢之市場數字-1)sii上市 2)otc上櫃 3)rotc興櫃 4)pub公開發行: '))
if market == 1:
    market = 'sii'
elif market == 2 :
    market = 'otc'
elif market == 3 :
    market = 'rotc'
elif market == 4 : #營業分析表
    market = 'pub'
else:
    print('type does not match')

#財報類型 #type
type = int(input('請輸入欲查詢之表格數字-1)損益表 2)資產負債表 3)現金流量表 4)營業分析表: '))
if type == 1: #損益表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb04'
elif type == 2 : #資產負債表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb05'
elif type == 3 : #現金流量表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb20'
elif type == 4 : #營業分析表
    url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb06'
else:
    print('type does not match')

#年份 #year
year = int(input('請輸入欲查詢年份: '))
if year >= 1000:
    year -= 1911

#季節 #season
season = input('請輸入欲查詢之季節:')

#網站連結

res = requests.post(url, {
                        'encodeURIComponent':1,
                        'step':1,
                        'firstin':1,
                        'off':1,
                        'TYPEK': market,            #input market(str)
                        'year':str(year),           #input market(str)
                        'season':str(season),
                        })

#把資料分別儲存至空變數中
if market == "sii" :
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表 #[0]表頭
    df_bank = pd.read_html(res.text)[1]      #[1]=銀行
    df_sec = pd.read_html(res.text)[2]       #[2]=證券
    df_normal = pd.read_html(res.text)[3]    #[3]=一般
    df_fh = pd.read_html(res.text)[4]        #[4]=金控
    df_ins = pd.read_html(res.text)[5]       #[5]=保險
    df_rare = pd.read_html(res.text)[6]      #[6]=異業
  else: #4)營業分析表
    df_all = pd.read_html(res.text)[0]  #[0]=全部行業；[1]=附註
    df_all.columns = df_all.iloc[0]
    df_all.columns = df_all.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt_all= df_all[df_all['公司代號'] != '公司代號'] #濾掉重複之表頭

elif market == "otc" :
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表 [0]表頭
    df_sec = pd.read_html(res.text)[1]  #[1]=證券
    df_normal = pd.read_html(res.text)[2]  #[2]=一般
  else: #4)營業分析表
    df_all = pd.read_html(res.text)[0]  #[0]=全部行業；[1]=附註
    df_all.columns = df_all.iloc[0]
    df_all.columns = df_all.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt_all= df_all[df_all['公司代號'] != '公司代號'] #濾掉重複之表頭

elif market == "rotc" :
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表 #[0]=表頭
    df_bank = pd.read_html(res.text)[1]      #[1]=銀行
    df_sec = pd.read_html(res.text)[2]      #[2]=證券
    df_normal = pd.read_html(res.text)[3]      #[3]=一般
    df_ins = pd.read_html(res.text)[4]      #[4]=保險
  else: #4)營業分析表
    df_all = pd.read_html(res.text)[0]  #[0]=全部行業；[1]=附註
    df_all.columns = df_all.iloc[0]
    df_all.columns = df_all.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt_all= df_all[df_all['公司代號'] != '公司代號'] #濾掉重複之表頭
else:
  if type == 1 or type == 2 or type == 3:  #1)損益表 2)資產負債表 3)現金流量表
    df_bank = pd.read_html(res.text)[1]  #[1]=銀行
    df_sec = pd.read_html(res.text)[2]  #[2]=證券
    df_normal = pd.read_html(res.text)[3]  #[3]=一般
    df_fh = pd.read_html(res.text)[4]  #[4]=金控
    df_ins = pd.read_html(res.text)[5]  #[5]=保險
  else: #4)營業分析表
    df_all = pd.read_html(res.text)[0]  #[0]=全部行業；[1]=附註
    df_all.columns = df_all.iloc[0]
    df_all.columns = df_all.columns.str.replace(' ', '') #將公司 代號，去除空格，成為公司代號
    filt_all= df_all[df_all['公司代號'] != '公司代號'] #濾掉重複之表頭

請輸入欲查詢之市場數字-1)sii上市 2)otc上櫃 3)rotc興櫃 4)pub公開發行: 2
請輸入欲查詢之表格數字-1)損益表 2)資產負債表 3)現金流量表 4)營業分析表: 2
請輸入欲查詢年份: 2022
請輸入欲查詢之季節:4

In [19]:
df_normal

,公司 代號,公司名稱,流動資產,非流動資產,資產總計,流動負債,非流動負債,負債總計,股本,權益─具證券性質之虛擬通貨,...,庫藏股票,歸屬於母公司業主之權益合計,共同控制下前手權益,合併前非屬共同控制股權,非控制權益,權益總計,待註銷股本股數（單位：股）,預收股款（權益項下）之約當發行股數（單位：股）,母公司暨子公司所持有之母公司庫藏股股數（單位：股）,每股參考淨值
0,1240,茂生農經,1331989,882265,2214254,864563,31939,896502,385982,--,...,--,1230443,--,--,87309,1317752,--,0,0,31.88
1,1259,安心,1972271,3352068,5324339,1713760,1605033,3318793,323895,--,...,0,1984924,--,--,20622,2005546,0,0,0,61.28
2,1264,德麥,2935176,1771441,4706617,989079,76306,1065385,370644,--,...,-2432,2934302,--,--,706930,3641232,0,0,12000,79.19
3,1268,漢來美食,2162752,4118476,6281228,1569438,2861335,4430773,427237,--,...,-65810,1850455,--,--,--,1850455,--,0,500000,43.83
4,1336,台翰,1503475,1270008,2773483,663872,386076,1049948,788184,--,...,--,1723535,--,--,--,1723535,0,0,0,21.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,9949,琉園,280503,191489,471992,46067,21395,67462,440334,--,...,0,404530,--,--,0,404530,0,0,0,9.19
800,9950,萬國通,1281216,3069267,4350483,1873692,2153130,4026822,1677160,--,...,--,300195,--,--,23466,323661,--,0,0,1.79
801,9951,皇田,3935919,1725458,5661377,1999810,287232,2287042,749000,--,...,--,3374335,--,--,--,3374335,0,0,0,45.05
802,9960,邁達康,858926,429920,1288846,535895,150004,685899,335925,--,...,0,602947,--,--,0,602947,0,0,0,17.95
803,9962,有益,1178795,315877,1494672,279927,11895,291822,902203,--,...,--,1202850,--,--,0,1202850,--,0,0,13.33